name: Build Windows with CMake

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chocolatey packages (OpenCL SDK)
        run: |
          choco install opencl-sdk --no-progress
          choco install zip --no-progress

      - name: Configure with CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir prmers_package
          copy build\Release\prmers.exe prmers_package\
          copy prmers.cl prmers_package\
          copy prmers_vload2.cl prmers_package\
          powershell Compress-Archive -Path prmers_package\* -DestinationPath prmers-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prmers-windows
          path: prmers-windows.zip
