name: Build Linux with OpenCL

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenCL and libcurl dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ocl-icd-opencl-dev opencl-headers libcurl4-openssl-dev libgmp-dev

      - name: Build with Makefile
        run: |
          export CXXFLAGS="-I/usr/include"
          export LDFLAGS="-L/usr/lib -lgmpxx -lgmp"
          make KERNEL_PATH=./kernels/
      - name: Package for release
        run: |
          mkdir -p prmers_package/kernels
          cp prmers prmers_package/
          cp kernels/prmers.cl prmers_package/kernels/
          tar -czvf prmers-linux.tar.gz -C prmers_package .

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: prmers-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate SHA256 checksum
        run: sha256sum prmers-linux.tar.gz > prmers-linux.tar.gz.sha256

      - name: Upload checksum to release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ✅ This release was built automatically via GitHub Actions from the source code in this repository.
            🔒 Each binary is accompanied by a `.sha256` checksum file for verification.
            💡 You can verify the integrity of the downloaded files using:
                sha256sum -c <filename>.sha256
            💡 You can view the build logs under the Actions tab.
          files: prmers-linux.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
