name: Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenCL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ocl-icd-opencl-dev opencl-headers

      - name: Build with Makefile
        run: make
