name: Build Windows with OpenCL

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install zip utility
        run: choco install zip --no-progress

      - name: Download Intel OpenCL SDK (headers + lib)
        run: |
          Invoke-WebRequest -Uri "https://github.com/intel/compute-runtime/releases/download/23.43.27141.41/opencl_headers_windows.zip" -OutFile opencl_headers_windows.zip
          Expand-Archive opencl_headers_windows.zip -DestinationPath opencl_sdk

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DOpenCL_INCLUDE_DIR=%GITHUB_WORKSPACE%\opencl_sdk\include -DOpenCL_LIBRARY=%GITHUB_WORKSPACE%\opencl_sdk\lib\OpenCL.lib

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir prmers_package
          copy build\Release\prmers.exe prmers_package\
          copy prmers.cl prmers_package\
          copy prmers_vload2.cl prmers_package\
          powershell Compress-Archive -Path prmers_package\* -DestinationPath prmers-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: prmers-windows
          path: prmers-windows.zip
