name: Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenCL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ocl-icd-opencl-dev opencl-headers

      - name: Build with Makefile
        run: make

      - name: Upload prmers binary
        uses: actions/upload-artifact@v4
        with:
          name: prmers-linux
          path: prmers
