name: Build Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux with Makefile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ocl-icd-opencl-dev zip make g++

      - name: Build with Makefile
        run: make PREFIX=/usr/local

      - name: Package binary and kernel files
        run: |
          mkdir prmers_package
          cp prmers prmers_package/
          cp prmers.cl prmers_package/
          cp prmers_vload2.cl prmers_package/
          zip -r prmers-linux.zip prmers_package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: prmers-linux
          path: prmers-linux.zip
