name: CMake Build Multi-Platform

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenCL (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y ocl-icd-opencl-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package binary
        run: |
          cd build
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            powershell Compress-Archive -Path prmers.exe -DestinationPath ../prmers-windows.zip
          else
            zip ../prmers-linux.zip prmers
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: prmers-${{ matrix.os }}
          path: |
            prmers-*.zip
